spring.application.name=bibflip-branching-service


#### properties for eureka client discovery
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

server.port=${SERVER_PORT:8092}

##Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Spring DataSource Configuration
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/branching}
spring.datasource.username= ${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:MrRobot4}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.database=postgresql
spring.jpa.show-sql=true

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=pe.upc.edu.bibflipbackend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Feign Client Configuration
feign.client.iam.name=bibflip-iam-service